// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyk7XFbYcuP9Yb89wJj33SmQEiMOWzI8k',
    appId: '1:45826552449:web:2212409c9391d681475380',
    messagingSenderId: '45826552449',
    projectId: 'newszone-663a4',
    authDomain: 'newszone-663a4.firebaseapp.com',
    storageBucket: 'newszone-663a4.appspot.com',
    measurementId: 'G-HX6FY2QS9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1dLi2mvZ6L83BiB6Hz0Tmrgfyh-n06YA',
    appId: '1:45826552449:android:829dd90ded8fc910475380',
    messagingSenderId: '45826552449',
    projectId: 'newszone-663a4',
    storageBucket: 'newszone-663a4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyk7XFbYcuP9Yb89wJj33SmQEiMOWzI8k',
    appId: '1:45826552449:web:eb30a1a88bb0df1e475380',
    messagingSenderId: '45826552449',
    projectId: 'newszone-663a4',
    authDomain: 'newszone-663a4.firebaseapp.com',
    storageBucket: 'newszone-663a4.appspot.com',
    measurementId: 'G-YSFWK5DD2R',
  );

}